######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 3 15:45:44 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindowimpl.h ui_mainwindow.h ../commonFiles/emf_ports.h
SOURCES += main.cpp mainwindowimpl.cpp
RESOURCES += emf_Interface.qrc
