#SRC=emf_client.c scheduling_handler.c recv_and_reassembler.c ha_cmd_handler.c emf_sock_lib_handler.c list_handler.c
#HEADER=emf.h


#OBJECTS=emf_client.o scheduling_handler.o recv_and_reassembler.o ha_cmd_handler.o emf_sock_lib_handler.o list_handler.o

gcc -o ./emf_client -g ./emf_client.c ./scheduling_handler.c ./recv_and_reassembler.c ./ha_cmd_handler.c ./emf_sock_lib_handler.c ./list_handler.c ./HandleSJBA.c	-lssl
